name: Create Release
on: 
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}

  build-and-upload:
    needs: [create-release]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: GOARCH=arm GOARM=6 GOOS=linux go build

      - name: Package code
        run: |
          mkdir light-controller_${{ github.ref_name }}_armhf
          mkdir -p light-controller_${{ github.ref_name }}_armhf/usr/local/bin
          mkdir -p light-controller_${{ github.ref_name }}_armhf/etc/systemd/system
          cp light-controller light-controller_${{ github.ref_name }}_armhf/usr/local/bin/
          cp light-controller.service light-controller_${{ github.ref_name }}_armhf/etc/systemd/system/

      - name: Package deb
        id: package-deb
        uses: cha-king/build-deb-action@v2.4.2
        with:
          package: light-controller
          package_root: light-controller_${{ github.ref_name }}_armhf
          maintainer: Charlie King
          version: ${{ github.ref_name }}
          arch: armhf
          desc: Simple MQTT light controller

      - name: Upload deb package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./${{ steps.package-deb.outputs.file_name }}
          asset_name: ${{ steps.package-deb.outputs.file_name }}
          asset_content_type: application/octet-stream
